spring:
  application:
    name: iot-device-management

  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

influxdb:
  url: http://localhost:8086
  token: wS88u1JEbCx3spiP26u3BEfoVMsBkXRV5xyBX3N9dbGvjdagTNFvUy1Zzo0-IkwSkHzwbb_iIri-1ppjEq1_nw==
  org: myorg
  bucket: device_telemetry

server:
  port: 8080