spring:
  application:
    name: iot-device-management
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/iot-device-management


  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

influxdb:
  url: http://localhost:8086
  token: lxgeRxdVMiqdvE1Feae905iOGLTmgp7opDcHiB5I0OeHVkqQ5XsNIOm8oTLLJAQGI9p4_l1S1IkPVOPRlgBDOw==
  org: myorg
  bucket: device_telemetry

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: master
    client-id: admin-cli
    username: admin
    password: admin123
  target-realm: iot-device-management

springdoc:
  swagger-ui:
    oauth:
      client-id: iot-backend
      client-secret: 1h1CUC3kXAzTD1n8x295cRW3eMyiyADv
      use-basic-authentication-with-access-code-grant: false

server:
  port: 8080