spring:
  application:
    name: iot-device-management
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/iot-device-management


  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

influxdb:
  url: http://localhost:8086
  token: MvE2nW6Z4GSjTJGsYY5r0gWmGbTXPSqTb3b9cc_e2BkzVmxFDA9mCsmoWcDzO-3s7WYFkLeaEXKk3O219y4atw==
  org: myorg
  bucket: device_telemetry

server:
  port: 8080